version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - artkirienko
  assignees:
  - artkirienko
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: capybara
    versions:
    - 3.35.1
    - 3.35.2
  - dependency-name: loofah
    versions:
    - 2.9.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - artkirienko
  assignees:
  - artkirienko
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - artkirienko
  assignees:
  - artkirienko
  ignore:
  - dependency-name: ruby
    versions:
    - 2.6.6.pre.stretch
